GET http://localhost:5050/posts
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmaXJzdE5hbWUiOiJDYXJvZ25hIiwibGFzdE5hbWUiOiJFciBDYW5lIiwiZW1haWwiOiJlbWFpbEBjYXJvZ25hLmNvbSIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNjk3ODMxNjg0LCJleHAiOjE2OTc5MTgwODR9.bWI0gwobme55ppJZ4MX4Ovc0RFDaRMOs01vvVkLUdoU
# Con l'estensione di REST CLIENT si può simulare una richiesta GET con la sintassi sopra segnalata, al path che decidiamo. 
# Per farne un altra sotto basta inserire 4 volte #

####

GET http://localhost:5050/posts?page=2&pageSize=3
# Per aggiungere le queries nell' url e cambiare pagina di ricerca si mettono dopo un ? e divise tra loro da &, scegliendone quindi il valore dopo l' =
# In questo caso sto dicendo che voglio vedere la pagina 2 con una grandezza delle pagine di 3.

####

GET http://localhost:5050

####

GET http://localhost:5050/posts/byId/652d7913c6ed0731475b1e04


####

POST http://localhost:5050/posts/create
Content-Type: application/json

{
    "title": "Post con referencing",
    "category": "Categoria x",
    "cover": "#",
    "price": 100,
    "rate": 4.2,
    "author": "652ff84eb7921505b91425b4"
}

####

PATCH http://localhost:5050/posts/update/652d7913c6ed0731475b1e04
Content-Type: application/json

{
    "title": "Primo post modificato daje",
    "category": "Categoria 1",
    "cover": "#",
    "price": 104,
    "rate": 5,
    "author": "Er Duca Pieppiolo"
}

####

DELETE http://localhost:5050/posts/delete/652d795cc6ed0731475b1e08

#####

GET http://localhost:5050/posts/bytitle?title=prova

####

GET http://localhost:5050/posts/bydate/2023-10-16

####

GET http://localhost:5050/users

####

POST http://localhost:5050/users/create 
Content-Type: application/json

{
    "firstName": "Carogna",
    "lastName": "Er Cane",
    "email": "email@carogna.com",
    "birthDay": "01/01/2001",
    "password": "HolaSalve",
    "role": "user",
    "avatar": "#"
}

####

POST http://localhost:5050/login HTTP/1.1
Content-Type: application/json

{
    "email": "email@carogna.com",
    "password": "HolaSalve"
}

####

POST http://localhost:5050/send-email HTTP/1.1
Content-Type: application/json

{
    "subject": "email confidenziale",
    "text": "salveeeeeee"
}